export const PERMISSION = {
  EVENTS_CREATE: "events:create",
  EVENTS_VIEW: "events:view",
  EVENTS_UPDATE: "events:update",
  EVENTS_DELETE: "events:delete",

  CATEGORIES_CREATE: "categories:create",
  CATEGORIES_UPDATE: "categories:update",
  CATEGORIES_DELETE: "categories:delete",
  CATEGORIES_VIEW: "categories:view",

  USERS_INVITE: "users:invite",
  USERS_VIEW: "users:view",
  USERS_UPDATE: "users:update",
  USERS_DELETE: "users:delete",
  USERS_SUSPEND: "users:suspend",

  INVITATIONS_VIEW: "invitations:view",

  ORGANISATIONS_VIEW: "organisations:view",
  ORGANISATIONS_CREATE: "organisations:create",
  ORGANISATIONS_UPDATE: "organisations:update",
  ORGANISATIONS_DELETE: "organisations:delete",

  ROLES_VIEW: "roles:view",
  ROLES_CREATE: "roles:create",
  ROLES_UPDATE: "roles:update",
  ROLES_DELETE: "roles:delete",
} as const;

export const PERMISSION_CATEGORY = {
  ORGANISATIONS: "Organisations",
  ROLES: "Roles",
  CATEGORIES: "Categories",
  INVITATIONS: "Invitations",
  EVENTS: "Events",
  USERS: "Users",
} as const;

export const PERMISSION_SCOPE = {
  OWN: "own",
  ORGANISATION: "organisation",
  ANY: "any",
} as const;

export const PERMISSION_CATEGORY_MAP: Record<Permission, PermissionCategory> = {
  [PERMISSION.CATEGORIES_CREATE]: PERMISSION_CATEGORY.CATEGORIES,
  [PERMISSION.CATEGORIES_DELETE]: PERMISSION_CATEGORY.CATEGORIES,
  [PERMISSION.CATEGORIES_UPDATE]: PERMISSION_CATEGORY.CATEGORIES,
  [PERMISSION.CATEGORIES_VIEW]: PERMISSION_CATEGORY.CATEGORIES,

  [PERMISSION.INVITATIONS_VIEW]: PERMISSION_CATEGORY.INVITATIONS,
  [PERMISSION.USERS_INVITE]: PERMISSION_CATEGORY.INVITATIONS,

  [PERMISSION.EVENTS_CREATE]: PERMISSION_CATEGORY.EVENTS,
  [PERMISSION.EVENTS_UPDATE]: PERMISSION_CATEGORY.EVENTS,
  [PERMISSION.EVENTS_DELETE]: PERMISSION_CATEGORY.EVENTS,
  [PERMISSION.EVENTS_VIEW]: PERMISSION_CATEGORY.EVENTS,

  [PERMISSION.USERS_VIEW]: PERMISSION_CATEGORY.USERS,
  [PERMISSION.USERS_UPDATE]: PERMISSION_CATEGORY.USERS,
  [PERMISSION.USERS_DELETE]: PERMISSION_CATEGORY.USERS,
  [PERMISSION.USERS_SUSPEND]: PERMISSION_CATEGORY.USERS,

  [PERMISSION.ORGANISATIONS_VIEW]: PERMISSION_CATEGORY.ORGANISATIONS,
  [PERMISSION.ORGANISATIONS_CREATE]: PERMISSION_CATEGORY.ORGANISATIONS,
  [PERMISSION.ORGANISATIONS_UPDATE]: PERMISSION_CATEGORY.ORGANISATIONS,
  [PERMISSION.ORGANISATIONS_DELETE]: PERMISSION_CATEGORY.ORGANISATIONS,

  [PERMISSION.ROLES_VIEW]: PERMISSION_CATEGORY.ROLES,
  [PERMISSION.ROLES_CREATE]: PERMISSION_CATEGORY.ROLES,
  [PERMISSION.ROLES_UPDATE]: PERMISSION_CATEGORY.ROLES,
  [PERMISSION.ROLES_DELETE]: PERMISSION_CATEGORY.ROLES,
};

export const PERMISSION_DESCRIPTION_MAP: Record<Permission, string> = {
  [PERMISSION.CATEGORIES_CREATE]: "Can create categories",
  [PERMISSION.CATEGORIES_DELETE]: "Can delete categories",
  [PERMISSION.CATEGORIES_UPDATE]: "Can update categories",
  [PERMISSION.CATEGORIES_VIEW]: "Can view categories",

  [PERMISSION.INVITATIONS_VIEW]: "Can view invitations",
  [PERMISSION.USERS_INVITE]: "Can invite users",

  [PERMISSION.EVENTS_VIEW]: "Can view events",
  [PERMISSION.EVENTS_CREATE]: "Can create events",
  [PERMISSION.EVENTS_UPDATE]: "Can update events",
  [PERMISSION.EVENTS_DELETE]: "Can delete events",

  [PERMISSION.USERS_VIEW]: "Can view users",
  [PERMISSION.USERS_UPDATE]: "Can update users",
  [PERMISSION.USERS_DELETE]: "Can delete users",
  [PERMISSION.USERS_SUSPEND]: "Can suspend users",

  [PERMISSION.ORGANISATIONS_VIEW]: "Can view organisations",
  [PERMISSION.ORGANISATIONS_CREATE]: "Can create organisations",
  [PERMISSION.ORGANISATIONS_UPDATE]: "Can update organisations",
  [PERMISSION.ORGANISATIONS_DELETE]: "Can delete organisations",

  [PERMISSION.ROLES_VIEW]: "Can view roles",
  [PERMISSION.ROLES_CREATE]: "Can create roles",
  [PERMISSION.ROLES_UPDATE]: "Can update roles",
  [PERMISSION.ROLES_DELETE]: "Can delete roles",
};

export const ALL_PERMISSIONS = Object.values(PERMISSION) as
  [Permission, ...Permission[]];

export const ALL_PERMISSION_CATEGORIES = Object.values(PERMISSION_CATEGORY) as
  [PermissionCategory, ...PermissionCategory[]];

export type Permission = (typeof PERMISSION)[keyof typeof PERMISSION];
export type PermissionCategory = (typeof PERMISSION_CATEGORY)[keyof typeof PERMISSION_CATEGORY];
export type PermissionScope = (typeof PERMISSION_SCOPE)[keyof typeof PERMISSION_SCOPE];