export const PERMISSIONS = {
  POSTS_CREATE: "posts:create",
  POSTS_VIEW: "posts:view",
  POSTS_UPDATE: "posts:update",
  POSTS_DELETE: "posts:delete",

  CATEGORIES_CREATE: "categories:create",
  CATEGORIES_UPDATE: "categories:update",
  CATEGORIES_DELETE: "categories:delete",
  CATEGORIES_VIEW: "categories:view",

  USERS_INVITE: "users:invite",
  USERS_VIEW: "users:view",
  USERS_UPDATE: "users:update",
  USERS_DELETE: "users:delete",
  USERS_SUSPEND: "users:suspend",

  INVITATIONS_VIEW: "invitations:view",

  ORGANISATIONS_VIEW: "organisations:view",
  ORGANISATIONS_CREATE: "organisations:create",
  ORGANISATIONS_UPDATE: "organisations:update",
  ORGANISATIONS_DELETE: "organisations:delete",

  ROLES_VIEW: "roles:view",
  ROLES_CREATE: "roles:create",
  ROLES_UPDATE: "roles:update",
  ROLES_DELETE: "roles:delete",
} as const;

export const PERMISSION_CATEGORIES = {
  ORGANISATIONS: "Organisations",
  ROLES: "Roles",
  CATEGORIES: "Categories",
  INVITATIONS: "Invitations",
  EVENTS: "Events",
  USERS: "Users",
} as const;

export const PERMISSION_CATEGORY_MAP: Record<Permission, PermissionCategory> = {
  [PERMISSIONS.CATEGORIES_CREATE]: PERMISSION_CATEGORIES.CATEGORIES,
  [PERMISSIONS.CATEGORIES_DELETE]: PERMISSION_CATEGORIES.CATEGORIES,
  [PERMISSIONS.CATEGORIES_UPDATE]: PERMISSION_CATEGORIES.CATEGORIES,
  [PERMISSIONS.CATEGORIES_VIEW]: PERMISSION_CATEGORIES.CATEGORIES,

  [PERMISSIONS.INVITATIONS_VIEW]: PERMISSION_CATEGORIES.INVITATIONS,
  [PERMISSIONS.USERS_INVITE]: PERMISSION_CATEGORIES.INVITATIONS,

  [PERMISSIONS.POSTS_CREATE]: PERMISSION_CATEGORIES.EVENTS,
  [PERMISSIONS.POSTS_UPDATE]: PERMISSION_CATEGORIES.EVENTS,
  [PERMISSIONS.POSTS_DELETE]: PERMISSION_CATEGORIES.EVENTS,
  [PERMISSIONS.POSTS_VIEW]: PERMISSION_CATEGORIES.EVENTS,

  [PERMISSIONS.USERS_VIEW]: PERMISSION_CATEGORIES.USERS,
  [PERMISSIONS.USERS_UPDATE]: PERMISSION_CATEGORIES.USERS,
  [PERMISSIONS.USERS_DELETE]: PERMISSION_CATEGORIES.USERS,
  [PERMISSIONS.USERS_SUSPEND]: PERMISSION_CATEGORIES.USERS,

  [PERMISSIONS.ORGANISATIONS_VIEW]: PERMISSION_CATEGORIES.ORGANISATIONS,
  [PERMISSIONS.ORGANISATIONS_CREATE]: PERMISSION_CATEGORIES.ORGANISATIONS,
  [PERMISSIONS.ORGANISATIONS_UPDATE]: PERMISSION_CATEGORIES.ORGANISATIONS,
  [PERMISSIONS.ORGANISATIONS_DELETE]: PERMISSION_CATEGORIES.ORGANISATIONS,

  [PERMISSIONS.ROLES_VIEW]: PERMISSION_CATEGORIES.ROLES,
  [PERMISSIONS.ROLES_CREATE]: PERMISSION_CATEGORIES.ROLES,
  [PERMISSIONS.ROLES_UPDATE]: PERMISSION_CATEGORIES.ROLES,
  [PERMISSIONS.ROLES_DELETE]: PERMISSION_CATEGORIES.ROLES,
};

export const PERMISSION_DESCRIPTION_MAP: Record<Permission, string> = {
  [PERMISSIONS.CATEGORIES_CREATE]: "Can create categories",
  [PERMISSIONS.CATEGORIES_DELETE]: "Can delete categories",
  [PERMISSIONS.CATEGORIES_UPDATE]: "Can update categories",
  [PERMISSIONS.CATEGORIES_VIEW]: "Can view categories",

  [PERMISSIONS.INVITATIONS_VIEW]: "Can view invitations",
  [PERMISSIONS.USERS_INVITE]: "Can invite users",

  [PERMISSIONS.POSTS_CREATE]: "Can create events",
  [PERMISSIONS.POSTS_UPDATE]: "Can update events",
  [PERMISSIONS.POSTS_DELETE]: "Can delete events",
  [PERMISSIONS.POSTS_VIEW]: "Can view events",

  [PERMISSIONS.USERS_VIEW]: "Can view users",
  [PERMISSIONS.USERS_UPDATE]: "Can update users",
  [PERMISSIONS.USERS_DELETE]: "Can delete users",
  [PERMISSIONS.USERS_SUSPEND]: "Can suspend users",

  [PERMISSIONS.ORGANISATIONS_VIEW]: "Can view organisations",
  [PERMISSIONS.ORGANISATIONS_CREATE]: "Can create organisations",
  [PERMISSIONS.ORGANISATIONS_UPDATE]: "Can update organisations",
  [PERMISSIONS.ORGANISATIONS_DELETE]: "Can delete organisations",

  [PERMISSIONS.ROLES_VIEW]: "Can view roles",
  [PERMISSIONS.ROLES_CREATE]: "Can create roles",
  [PERMISSIONS.ROLES_UPDATE]: "Can update roles",
  [PERMISSIONS.ROLES_DELETE]: "Can delete roles",
};

export const ALL_PERMISSIONS = Object.values(PERMISSIONS) as
  [Permission, ...Permission[]];

export const ALL_PERMISSION_CATEGORIES = Object.values(PERMISSION_CATEGORIES) as
  [PermissionCategory, ...PermissionCategory[]];

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
export type PermissionCategory = (typeof PERMISSION_CATEGORIES)[keyof typeof PERMISSION_CATEGORIES];