export const env = {
  NODE_ENV: process.env.NODE_ENV,
  FRONTEND_URL: process.env.FRONTEND_URL,

  SUPER_ADMIN_NAME: process.env.ADMIN_NAME,
  SUPER_ADMIN_EMAIL: process.env.ADMIN_EMAIL,
  SUPER_ADMIN_PASSWORD: process.env.ADMIN_PASSWORD,

  DATABASE_URL: process.env.DATABASE_URL,

  GOOGLE_MAIL_USER: process.env.GOOGLE_MAIL_USER,
  GOOGLE_APP_PASSWORD: process.env.GOOGLE_APP_PASSWORD,

  JWT_SECRET: process.env.JWT_SECRET,
  INVITATION_JWT_SECRET: process.env.INVITATION_JWT_SECRET,
  CRON_SECRET: process.env.CRON_SECRET,

  CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET,
  CLOUDINARY_UPLOAD_FOLDER: process.env.CLOUDINARY_UPLOAD_FOLDER,
};